### ISSUE TITLE
Hide months =< 2016-08 from membership list

### ISSUE THREAD

**Issue by stigtsp** [dimsumlabs/dsl-accounts#9]
we started counting mid august.

**Comment by hamishcoleman** [comment]
Should be easy enough to do - the code is all set up for additive filtering to be applied.  It was my expectation that we would need filtering when the width of the list was too wide to fit on the screen.

Perhaps - instead of making a special case out of the epoch date, we could just wait until the width did require it to be filtered

**Comment by adisbladis** [comment]
Fixed in f1cb6cac7583ed4cabb12012e2403972edc94bd0
